/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RelatorioRouteImport } from './routes/relatorio'
import { Route as ComparacaoRouteImport } from './routes/comparacao'
import { Route as IndexRouteImport } from './routes/index'

const RelatorioRoute = RelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparacaoRoute = ComparacaoRouteImport.update({
  id: '/comparacao',
  path: '/comparacao',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comparacao': typeof ComparacaoRoute
  '/relatorio': typeof RelatorioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comparacao': typeof ComparacaoRoute
  '/relatorio': typeof RelatorioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comparacao': typeof ComparacaoRoute
  '/relatorio': typeof RelatorioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/comparacao' | '/relatorio'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/comparacao' | '/relatorio'
  id: '__root__' | '/' | '/comparacao' | '/relatorio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComparacaoRoute: typeof ComparacaoRoute
  RelatorioRoute: typeof RelatorioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/relatorio': {
      id: '/relatorio'
      path: '/relatorio'
      fullPath: '/relatorio'
      preLoaderRoute: typeof RelatorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparacao': {
      id: '/comparacao'
      path: '/comparacao'
      fullPath: '/comparacao'
      preLoaderRoute: typeof ComparacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComparacaoRoute: ComparacaoRoute,
  RelatorioRoute: RelatorioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
